#![allow(clippy::unwrap_used)]
#![allow(missing_docs)]
//! Streamable-HTTP TLS smoke: spawn the binary with --tls-cert/--tls-key,
//! perform a real rustls handshake against it (trusting only the self-signed
//! cert generated by rcgen), and exercise an authenticated `initialize`.

#![cfg(feature = "tls")]

mod common;
use common::{
    BoundedLines, Server, binary_path, ensure_built, parse_first_sse_data, pick_port, wait_for_port,
};
use serde_json::{Value, json};
use std::io::BufReader;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::Arc;
use std::time::Duration;

/// Poll until TCP connections to `port` are accepted, or panic after `timeout`.
fn write_self_signed(dir: &Path) -> (PathBuf, PathBuf) {
    let issued = rcgen::generate_simple_self_signed(vec!["localhost".into()]).unwrap();
    let cert_path = dir.join("cert.pem");
    let key_path = dir.join("key.pem");
    std::fs::write(&cert_path, issued.cert.pem()).unwrap();
    std::fs::write(&key_path, issued.signing_key.serialize_pem()).unwrap();
    // The hardened loader (mecmcp-transport, plan decision D2) refuses a private
    // key readable by group or other, and exits rather than serving with the key
    // exposed. `fs::write` creates 0644 under a typical umask, so without this
    // the server never starts and the test fails with "did not start within 15s"
    // rather than anything pointing at permissions.
    //
    // This is the same step an operator must take on upgrade — it is not test
    // scaffolding around an inconvenience.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(&key_path, std::fs::Permissions::from_mode(0o600)).unwrap();
    }
    (cert_path, key_path)
}

fn spawn_tls(inv_path: &Path, tokens_path: &Path, cert: &Path, key: &Path) -> Server {
    let port = pick_port();
    let device_lease_dir = tempfile::tempdir().expect("create device lease directory");
    let state_file = device_lease_dir.path().join("changeset-state.json");
    let mut child = Command::new(binary_path())
        .args([
            "-f",
            inv_path.to_str().unwrap(),
            "-t",
            "streamable-http",
            "-H",
            "127.0.0.1",
            "-p",
            &port.to_string(),
            "--tokens-file",
            tokens_path.to_str().unwrap(),
            "--tls-cert",
            cert.to_str().unwrap(),
            "--tls-key",
            key.to_str().unwrap(),
            "--device-lease-dir",
            device_lease_dir.path().to_str().unwrap(),
            "--state-file",
            state_file.to_str().unwrap(),
        ])
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn");
    let stderr = child.stderr.take().unwrap();
    // Bounded on a worker thread — a deadline checked between `read_line` calls
    // cannot fire, because the missing line is exactly what leaves `read_line`
    // blocked. See `common::BoundedLines`.
    let lines = BoundedLines::spawn(BufReader::new(stderr));
    // Matches both "(TLS)" and the plain HTTP variant; for this test only the
    // TLS line is emitted.
    if !lines.wait_for(Duration::from_secs(15), |line| {
        line.contains("streamable-http listening")
    }) {
        let _ = child.kill();
        panic!(
            "server did not print the 'streamable-http listening' readiness line within 15s \
             (if the server still works, the log line was renamed — see http_transport.rs)"
        );
    }
    // The BoundedLines worker already owns this pipe and keeps reading it, so it
    // is the drain. Do not join it — it blocks in `read_line` and would only
    // notice a dropped receiver on its next send. See `common::into_drain`.
    let drain = lines.into_drain();
    // Wait for the TLS socket to actually accept connections — the stderr
    // readiness line can fire before the listener is fully ready.
    wait_for_port(port, Duration::from_secs(5));

    Server {
        child,
        port,
        _stderr_drain: drain,
        _device_lease_dir: device_lease_dir,
    }
}

fn build_tls_agent(cert_pem_path: &Path) -> ureq::Agent {
    use rustls_pki_types::CertificateDer;
    use rustls_pki_types::pem::PemObject;
    let pem = std::fs::read(cert_pem_path).unwrap();
    let mut roots = rustls::RootCertStore::empty();
    for cert in CertificateDer::pem_slice_iter(&pem) {
        roots.add(cert.unwrap()).unwrap();
    }
    // Ensure a default crypto provider is installed in the test process too.
    let _ = rustls::crypto::ring::default_provider().install_default();
    let cfg = rustls::ClientConfig::builder()
        .with_root_certificates(roots)
        .with_no_client_auth();
    ureq::AgentBuilder::new().tls_config(Arc::new(cfg)).build()
}

#[test]
fn tls_handshake_completes_and_auth_works() {
    ensure_built();
    let dir = tempfile::tempdir().unwrap();
    let inv = dir.path().join("inv.json");
    common::write_restricted(
        &inv,
        r#"{"r1":{"ip":"203.0.113.1","port":1,"username":"u","auth":{"type":"password","password":"x"}}}"#,
    );
    let toks = dir.path().join("tokens.json");
    let (cert, key) = write_self_signed(dir.path());

    // Mint an unscoped token.
    let mint = Command::new(binary_path())
        .args([
            "token",
            "add",
            "--tokens-file",
            toks.to_str().unwrap(),
            "--name",
            "all",
            "--routers",
            "*",
            "--tools",
            "*",
        ])
        .output()
        .unwrap();
    assert!(
        mint.status.success(),
        "token add failed: stderr={}",
        String::from_utf8_lossy(&mint.stderr)
    );
    let secret = String::from_utf8(mint.stdout).unwrap().trim().to_string();
    assert!(!secret.is_empty(), "minted secret should not be empty");

    let server = spawn_tls(&inv, &toks, &cert, &key);
    let agent = build_tls_agent(&cert);
    // Use "localhost" so the SAN in the rcgen cert matches; bind is 127.0.0.1
    // but that resolves to the loopback the server is listening on.
    let url = format!("https://localhost:{}/mcp", server.port);

    let resp = agent
        .post(&url)
        .set("Authorization", &format!("Bearer {}", secret))
        .set("Content-Type", "application/json")
        .set("Accept", "application/json, text/event-stream")
        .send_json(json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "protocolVersion": "2025-03-26",
                "capabilities": {},
                "clientInfo": {"name": "tls-smoke", "version": "0"}
            }
        }))
        .expect("TLS POST");

    assert_eq!(resp.status(), 200);
    let content_type = resp.header("Content-Type").unwrap_or("").to_string();
    let text = resp.into_string().unwrap_or_default();
    let body: Value = if content_type.contains("text/event-stream") {
        parse_first_sse_data(&text).unwrap_or(json!({}))
    } else {
        serde_json::from_str(&text).unwrap_or(json!({}))
    };
    assert!(
        body.pointer("/result").is_some(),
        "expected initialize result, got body: {body}"
    );
}

#[test]
fn tls_rejects_request_without_token() {
    ensure_built();
    let dir = tempfile::tempdir().unwrap();
    let inv = dir.path().join("inv.json");
    common::write_restricted(
        &inv,
        r#"{"r1":{"ip":"203.0.113.1","port":1,"username":"u","auth":{"type":"password","password":"x"}}}"#,
    );
    let toks = dir.path().join("tokens.json");
    common::write_restricted(&toks, r#"{"version":1,"tokens":[]}"#);
    // Token files must be mode 0600 (mecmcp-auth permission check)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&toks, std::fs::Permissions::from_mode(0o600))
            .expect("chmod token file");
    }
    let (cert, key) = write_self_signed(dir.path());

    let server = spawn_tls(&inv, &toks, &cert, &key);
    let agent = build_tls_agent(&cert);
    let url = format!("https://localhost:{}/mcp", server.port);

    let result = agent
        .post(&url)
        .set("Content-Type", "application/json")
        .set("Accept", "application/json, text/event-stream")
        .send_json(json!({"jsonrpc": "2.0", "id": 1, "method": "tools/list", "params": {}}));
    let code = match result {
        Ok(resp) => resp.status(),
        Err(ureq::Error::Status(code, _)) => code,
        Err(e) => panic!("transport error: {e}"),
    };
    assert_eq!(code, 401);
}
